logFilters:
  # We're installing multiple versions of React, and we don't want to see the warnings about it.
  - text: "react is listed by your project with version 18.2.0, which doesn't satisfy what react-dom (p1eae0) and other dependencies request (but they have non-overlapping ranges!)."
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 24a2171abe511205f3184779105076031ca8daefb3fecb744e3d4f3f4010785881127bfc2d73445f7f101bf200d4a5931ec75feb543e50ffbf584da53a2f62cf
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v0.1.3/bundles/@yarnpkg/plugin-nolyfill.js"
